# Generated by Django 4.2.11 on 2024-07-08 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solar_kw_production", models.FloatField()),
                ("battery_kw_production", models.FloatField()),
                ("panel_pricing", models.FloatField()),
                ("battery_pricing", models.FloatField()),
                ("inverter_pricing", models.FloatField()),
                ("panels_required_pdf", models.IntegerField()),
                ("house_consumption_pdf", models.FloatField()),
                ("battries_required_pdf", models.FloatField()),
                ("required_inverter_pdf", models.IntegerField()),
                ("total_cost", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.userdetail",
                    ),
                ),
            ],
        ),
    ]
